plugins {
	id 'dev.kikugie.stonecutter'
	id 'fabric-loom' version '1.9.2'
	id 'maven-publish'
}

version = "${project.mod_version}+${stonecutter.current.version}"
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-${stonecutter.current.version}-fabric"
}

def javaNumber = project.java_version.toString()
def javaVer = JavaVersion.toVersion(javaNumber)
def repoDir = file("../..")

loom {
	accessWidenerPath = new File(repoDir, "src/main/resources/keyboard_workstations.accesswidener")

	runConfigs.configureEach {
		ideConfigGenerated = true
		runDir = new File(repoDir, "run")
	}
}

repositories {
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${stonecutter.current.version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
	def props = [
			version       : project.version,
			minecraft     : project.minecraft_dep,
			java          : javaNumber,
			loader        : project.loader_version,
			fabric_api_id : project.fabric_api_id
	]

	inputs.properties props

	filesMatching("fabric.mod.json") {
		expand props
	}

	def mc = stonecutter.current.version.toString()

	if (mc == "1.16.5") {
		exclude "data/minecraft/tags/blocks/mineable/**"
	}

	if (mc == "1.21.1") {
		filesMatching("data/**/recipes/**") {
			filter { String line ->
				line.replaceAll(/"item": "(keyboard_workstations:[^"]+)"/, '"id": "$1"')
			}
		}

		eachFile { details ->
			details.path = details.path
					.replace("/recipes/", "/recipe/")
					.replace("/loot_tables/", "/loot_table/")
					.replace("/tags/blocks/", "/tags/block/")
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = javaNumber as int
	it.options.compilerArgs << "-Xmaxerrs" << "1000"
}

java {
	withSourcesJar()

	sourceCompatibility = javaVer
	targetCompatibility = javaVer

	toolchain {
		languageVersion = JavaLanguageVersion.of(javaNumber)
	}
}

jar {
	manifest {
		attributes 'Implementation-Title': project.archives_base_name,
				'Implementation-Version': project.version
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}
