org.gradle.jvmargs=-Xmx1536M
org.gradle.parallel=false
org.gradle.daemon=false

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties: https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.0.0
maven_group=dev.keyboard
archives_base_name=keyboard_workstations

# Dependencies
fabric_api_version=0.145.1+26.1
