pluginManagement {
repositories {
maven {
name = 'Aliyun'
url = 'https://maven.aliyun.com/repository/public'
}
maven {
name = 'Aliyun Gradle Plugin'
url = 'https://maven.aliyun.com/repository/gradle-plugin'
}
maven {
name = 'Fabric'
url = 'https://maven.fabricmc.net/'
}
mavenCentral()
gradlePluginPortal()
}
}

rootProject.name = 'keyboard_workstations'
