plugins {
	id("dev.kikugie.stonecutter")
}

stonecutter active "1.20.1"

stonecutter parameters {
	swaps["minecraft"] = "\"${node.metadata.version}\";"

	// Yarn names in the shared source become Mojang official names only on 26.1, which has no Yarn.
	replacements {
		string(current.parsed >= "26.1") {
			replace("accessWidener	v2	named", "accessWidener	v2	official")

			replace("net.minecraft.block.SaplingGenerator", "net.minecraft.world.level.block.grower.TreeGrower")
			replace("net/minecraft/block/SaplingGenerator", "net/minecraft/world/level/block/grower/TreeGrower")
			replace("net/minecraft/block/SaplingBlock", "net/minecraft/world/level/block/SaplingBlock")
			replace("	generator	", "	treeGrower	")
			replace("	megaVariant	", "	megaTree	")
			replace("	regularVariant	", "	tree	")

			replace("net.minecraft.server.world.ServerWorld", "net.minecraft.server.level.ServerLevel")
			replace("net.minecraft.world.WorldView", "net.minecraft.world.level.LevelReader")
			replace("net.minecraft.world.WorldAccess", "net.minecraft.world.level.LevelAccessor")
			replace("net.minecraft.world.BlockView", "net.minecraft.world.level.BlockGetter")
			replace("net.minecraft.world.WorldEvents", "net.minecraft.world.level.block.LevelEvent")
			replace("net.minecraft.world.World", "net.minecraft.world.level.Level")
			replace("net.minecraft.util.Identifier", "net.minecraft.resources.Identifier")
			replace("net.minecraft.nbt.NbtCompound", "net.minecraft.nbt.CompoundTag")
			replace("net.minecraft.nbt.NbtList", "net.minecraft.nbt.ListTag")
			replace("net.minecraft.nbt.NbtElement", "net.minecraft.nbt.Tag")
			replace("net.minecraft.text.MutableText", "net.minecraft.network.chat.MutableComponent")
			replace("net.minecraft.text.Text", "net.minecraft.network.chat.Component")
			replace("net.minecraft.server.network.ServerPlayerEntity", "net.minecraft.server.level.ServerPlayer")
			replace("net.minecraft.entity.player.PlayerEntity", "net.minecraft.world.entity.player.Player")
			replace("net.minecraft.entity.player.PlayerInventory", "net.minecraft.world.entity.player.Inventory")
			replace("net.minecraft.entity.passive.AbstractHorseEntity", "net.minecraft.world.entity.animal.equine.AbstractHorse")
			replace("net.minecraft.entity.passive.AnimalEntity", "net.minecraft.world.entity.animal.Animal")
			replace("net.minecraft.entity.passive.CowEntity", "net.minecraft.world.entity.animal.cow.Cow")
			replace("net.minecraft.entity.passive.PassiveEntity", "net.minecraft.world.entity.AgeableMob")
			replace("net.minecraft.entity.passive.TameableEntity", "net.minecraft.world.entity.TamableAnimal")
			replace("net.minecraft.entity.passive.VillagerEntity", "net.minecraft.world.entity.npc.villager.Villager")
			replace("net.minecraft.block.SaplingBlock", "net.minecraft.world.level.block.SaplingBlock")
			replace("net.minecraft.item.BoneMealItem", "net.minecraft.world.item.BoneMealItem")
			replace("net.minecraft.client.network.ClientPlayerEntity", "net.minecraft.client.player.LocalPlayer")
			replace("net.minecraft.util.math.ChunkSectionPos", "net.minecraft.core.SectionPos")
			replace("net.minecraft.entity.mob.MobEntity", "net.minecraft.world.entity.Mob")
			replace("net.minecraft.entity.ItemEntity", "net.minecraft.world.entity.item.ItemEntity")
			replace("net.minecraft.entity.LivingEntity", "net.minecraft.world.entity.LivingEntity")
			replace("net.minecraft.entity.EntityType", "net.minecraft.world.entity.EntityType")
			replace("net.minecraft.entity.SpawnGroup", "net.minecraft.world.entity.MobCategory")
			replace("net.minecraft.entity.Shearable", "net.minecraft.world.entity.Shearable")
			replace("net.minecraft.entity.Entity", "net.minecraft.world.entity.Entity")
			replace("net.minecraft.entity.data.TrackedDataHandlerRegistry", "net.minecraft.network.syncher.EntityDataSerializers")
			replace("net.minecraft.entity.data.TrackedDataHandler", "net.minecraft.network.syncher.EntityDataSerializer")
			replace("net.minecraft.entity.ai.pathing.LandPathNodeMaker", "net.minecraft.world.level.pathfinder.WalkNodeEvaluator")
			replace("net.minecraft.entity.ai.pathing.PathNodeNavigator", "net.minecraft.world.level.pathfinder.PathFinder")
			replace("net.minecraft.entity.ai.pathing.MobNavigation", "net.minecraft.world.entity.ai.navigation.GroundPathNavigation")
			replace("net.minecraft.entity.ai.pathing.PathNodeType", "net.minecraft.world.level.pathfinder.PathType")
			replace("net.minecraft.entity.ai.pathing.Path", "net.minecraft.world.level.pathfinder.Path")
			replace("net.minecraft.block.entity.BlockEntityTicker", "net.minecraft.world.level.block.entity.BlockEntityTicker")
			replace("net.minecraft.block.entity.BlockEntityType", "net.minecraft.world.level.block.entity.BlockEntityType")
			replace("net.minecraft.block.entity.BlockEntity", "net.minecraft.world.level.block.entity.BlockEntity")
			replace("net.minecraft.block.entity.LootableContainerBlockEntity", "net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity")
			replace("net.minecraft.block.piston.PistonBehavior", "net.minecraft.world.level.material.PushReaction")
			replace("AbstractBlock.Settings.create()", "BlockBehaviour.Properties.of()")
			replace("AbstractBlock.Settings", "BlockBehaviour.Properties")
			replace("IntProperty.of", "IntegerProperty.create")
			replace("net.minecraft.entity.ai.pathing.PathContext", "net.minecraft.world.level.pathfinder.PathfindingContext")
			replace("net.minecraft.block.AbstractBlock", "net.minecraft.world.level.block.state.BlockBehaviour")
			replace("net.minecraft.block.AttachedStemBlock", "net.minecraft.world.level.block.AttachedStemBlock")
			replace("net.minecraft.block.BlockRenderType", "net.minecraft.world.level.block.RenderShape")
			replace("net.minecraft.block.BlockState", "net.minecraft.world.level.block.state.BlockState")
			replace("net.minecraft.block.BlockWithEntity", "net.minecraft.world.level.block.BaseEntityBlock")
			replace("net.minecraft.block.CropBlock", "net.minecraft.world.level.block.CropBlock")
			replace("net.minecraft.block.FenceGateBlock", "net.minecraft.world.level.block.FenceGateBlock")
			replace("net.minecraft.block.MapColor", "net.minecraft.world.level.material.MapColor")
			replace("net.minecraft.block.ShapeContext", "net.minecraft.world.phys.shapes.CollisionContext")
			replace("net.minecraft.block.Blocks", "net.minecraft.world.level.block.Blocks")
			replace("net.minecraft.block.Block", "net.minecraft.world.level.block.Block")
			replace("net.minecraft.item.ItemPlacementContext", "net.minecraft.world.item.context.BlockPlaceContext")
			replace("net.minecraft.item.BlockItem", "net.minecraft.world.item.BlockItem")
			replace("net.minecraft.item.ItemGroup", "net.minecraft.world.item.CreativeModeTab")
			replace("net.minecraft.item.ItemStack", "net.minecraft.world.item.ItemStack")
			replace("net.minecraft.item.Items", "net.minecraft.world.item.Items")
			replace("net.minecraft.item.Item", "net.minecraft.world.item.Item")
			replace("net.minecraft.inventory.SimpleInventory", "net.minecraft.world.SimpleContainer")
			replace("net.minecraft.inventory.Inventories", "net.minecraft.world.ContainerHelper")
			replace("net.minecraft.inventory.Inventory", "net.minecraft.world.Container")
			replace("net.minecraft.screen.GenericContainerScreenHandler", "net.minecraft.world.inventory.ChestMenu")
			replace("net.minecraft.screen.NamedScreenHandlerFactory", "net.minecraft.world.MenuProvider")
			replace("net.minecraft.screen.ScreenHandler", "net.minecraft.world.inventory.AbstractContainerMenu")
			replace("net.minecraft.screen.ScreenTexts", "net.minecraft.network.chat.CommonComponents")
			replace("net.minecraft.sound.BlockSoundGroup", "net.minecraft.world.level.block.SoundType")
			replace("net.minecraft.sound.SoundCategory", "net.minecraft.sounds.SoundSource")
			replace("net.minecraft.sound.SoundEvents", "net.minecraft.sounds.SoundEvents")
			replace("net.minecraft.sound.SoundEvent", "net.minecraft.sounds.SoundEvent")
			replace("net.minecraft.state.property.DirectionProperty", "net.minecraft.world.level.block.state.properties.EnumProperty")
			replace("net.minecraft.state.property.Properties", "net.minecraft.world.level.block.state.properties.BlockStateProperties")
			replace("net.minecraft.state.StateManager", "net.minecraft.world.level.block.state.StateDefinition")
			replace("net.minecraft.registry.tag.BlockTags", "net.minecraft.tags.BlockTags")
			replace("net.minecraft.registry.Registries", "net.minecraft.core.registries.BuiltInRegistries")
			replace("net.minecraft.registry.Registry", "net.minecraft.core.Registry")
			replace("net.minecraft.util.math.random.Random", "net.minecraft.util.RandomSource")
			replace("net.minecraft.util.math.BlockBox", "net.minecraft.world.level.levelgen.structure.BoundingBox")
			replace("net.minecraft.util.math.BlockPos", "net.minecraft.core.BlockPos")
			replace("net.minecraft.util.math.Direction", "net.minecraft.core.Direction")
			replace("net.minecraft.util.math.MathHelper", "net.minecraft.util.Mth")
			replace("net.minecraft.util.math.RotationAxis", "com.mojang.math.Axis")
			replace("net.minecraft.util.math.Vec3d", "net.minecraft.world.phys.Vec3")
			replace("net.minecraft.util.math.Box", "net.minecraft.world.phys.AABB")
			replace("net.minecraft.util.shape.VoxelShape", "net.minecraft.world.phys.shapes.VoxelShape")
			replace("net.minecraft.util.collection.DefaultedList", "net.minecraft.core.NonNullList")
			replace("net.minecraft.util.ActionResult", "net.minecraft.world.InteractionResult")
			replace("net.minecraft.util.BlockMirror", "net.minecraft.world.level.block.Mirror")
			replace("net.minecraft.util.BlockRotation", "net.minecraft.world.level.block.Rotation")
			replace("net.minecraft.util.Formatting", "net.minecraft.ChatFormatting")
			replace("net.minecraft.util.Hand", "net.minecraft.world.InteractionHand")
			replace("net.minecraft.util.ItemScatterer", "net.minecraft.world.Containers")
			replace("net.minecraft.util.hit.BlockHitResult", "net.minecraft.world.phys.BlockHitResult")
			replace("net.minecraft.network.listener.ClientPlayPacketListener", "net.minecraft.network.protocol.game.ClientGamePacketListener")
			replace("net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket", "net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket")
			replace("net.minecraft.network.packet.CustomPayload", "net.minecraft.network.protocol.common.custom.CustomPacketPayload")
			replace("net.minecraft.network.codec.PacketCodecs", "net.minecraft.network.codec.ByteBufCodecs")
			replace("net.minecraft.network.codec.PacketCodec", "net.minecraft.network.codec.StreamCodec")
			replace("net.minecraft.network.RegistryByteBuf", "net.minecraft.network.RegistryFriendlyByteBuf")
			replace("net.minecraft.network.PacketByteBuf", "net.minecraft.network.FriendlyByteBuf")
			replace("net.minecraft.network.packet.Packet", "net.minecraft.network.protocol.Packet")
			replace("net.minecraft.client.gui.DrawContext", "net.minecraft.client.gui.GuiGraphicsExtractor")
			replace("net.minecraft.client.gui.tooltip.Tooltip", "net.minecraft.client.gui.components.Tooltip")
			replace("net.minecraft.client.gui.widget.ButtonWidget", "net.minecraft.client.gui.components.Button")
			replace("net.minecraft.client.gui.widget.ClickableWidget", "net.minecraft.client.gui.components.AbstractWidget")
			replace("net.minecraft.client.gui.widget.ElementListWidget", "net.minecraft.client.gui.components.ObjectSelectionList")
			replace("net.minecraft.client.gui.widget.SliderWidget", "net.minecraft.client.gui.components.AbstractSliderButton")
			replace("net.minecraft.client.gui.screen.Screen", "net.minecraft.client.gui.screens.Screen")
			replace("net.minecraft.client.gui.Selectable", "net.minecraft.client.gui.narration.NarratableEntry")
			replace("net.minecraft.client.gui.Element", "net.minecraft.client.gui.components.events.GuiEventListener")
			replace("net.minecraft.client.option.KeyBinding", "net.minecraft.client.KeyMapping")
			replace("net.minecraft.client.util.InputUtil", "com.mojang.blaze3d.platform.InputConstants")
			replace("net.minecraft.client.util.math.MatrixStack", "com.mojang.blaze3d.vertex.PoseStack")
			replace("MatrixStack.Entry", "PoseStack.Pose")
			replace("net.minecraft.client.render.model.json.ModelTransformationMode", "net.minecraft.world.item.ItemDisplayContext")
			replace("net.minecraft.client.render.block.entity.BlockEntityRendererFactory", "net.minecraft.client.renderer.blockentity.BlockEntityRendererProvider")
			replace("net.minecraft.client.render.block.entity.BlockEntityRenderer", "net.minecraft.client.renderer.blockentity.BlockEntityRenderer")
			replace("net.minecraft.client.render.entity.feature.FeatureRendererContext", "net.minecraft.client.renderer.entity.RenderLayerParent")
			replace("net.minecraft.client.render.entity.feature.FeatureRenderer", "net.minecraft.client.renderer.entity.layers.RenderLayer")
			replace("net.minecraft.client.render.entity.model.EntityModelLayers", "net.minecraft.client.model.geom.ModelLayers")
			replace("net.minecraft.client.render.entity.EntityRendererFactory", "net.minecraft.client.renderer.entity.EntityRendererProvider")
			replace("net.minecraft.client.render.entity.EntityRenderDispatcher", "net.minecraft.client.renderer.entity.EntityRenderDispatcher")
			replace("net.minecraft.client.render.entity.MobEntityRenderer", "net.minecraft.client.renderer.entity.MobRenderer")
			replace("net.minecraft.client.render.entity.EntityRenderer", "net.minecraft.client.renderer.entity.EntityRenderer")
			replace("net.minecraft.client.render.OverlayTexture", "net.minecraft.client.renderer.texture.OverlayTexture")
			replace("net.minecraft.client.render.RenderLayer", "net.minecraft.client.renderer.rendertype.RenderType")
			replace("net.minecraft.client.render.VertexConsumerProvider", "net.minecraft.client.renderer.MultiBufferSource")
			replace("net.minecraft.client.render.VertexConsumer", "com.mojang.blaze3d.vertex.VertexConsumer")
			replace("net.minecraft.client.MinecraftClient", "net.minecraft.client.Minecraft")
			replace("net.minecraft.world.event.GameEvent", "net.minecraft.world.level.gameevent.GameEvent")

			replace("net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup", "net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab")
			replace("net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper", "net.fabricmc.fabric.api.client.keymapping.v1.KeyMappingHelper")
			replace("net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap", "net.fabricmc.fabric.api.client.rendering.v1.ChunkSectionLayerMap")
			replace("net.fabricmc.fabric.api.networking.v1.PacketByteBufs", "net.fabricmc.fabric.api.networking.v1.FriendlyByteBufs")

			replace("net.minecraft.particle.BlockStateParticleEffect", "net.minecraft.core.particles.BlockParticleOption")
			replace("net.minecraft.particle.ParticleTypes", "net.minecraft.core.particles.ParticleTypes")
			replace("net.minecraft.entity.ai.goal.LookAtEntityGoal", "net.minecraft.world.entity.ai.goal.LookAtPlayerGoal")
			replace("net.minecraft.entity.ai.goal.LookAroundGoal", "net.minecraft.world.entity.ai.goal.RandomLookAroundGoal")
			replace("net.minecraft.entity.ai.goal.SwimGoal", "net.minecraft.world.entity.ai.goal.FloatGoal")
			replace("net.minecraft.entity.ai.pathing.EntityNavigation", "net.minecraft.world.entity.ai.navigation.PathNavigation")
			replace("net.minecraft.entity.ai.pathing.NavigationType", "net.minecraft.world.level.pathfinder.PathComputationType")
			replace("net.minecraft.entity.attribute.DefaultAttributeContainer", "net.minecraft.world.entity.ai.attributes.AttributeSupplier")
			replace("net.minecraft.entity.attribute.EntityAttributes", "net.minecraft.world.entity.ai.attributes.Attributes")
			replace("net.minecraft.entity.data.DataTracker", "net.minecraft.network.syncher.SynchedEntityData")
			replace("net.minecraft.entity.data.TrackedData", "net.minecraft.network.syncher.EntityDataAccessor")
			replace("net.minecraft.entity.damage.DamageSource", "net.minecraft.world.damagesource.DamageSource")
			replace("net.minecraft.entity.mob.PathAwareEntity", "net.minecraft.world.entity.PathfinderMob")
			replace("net.minecraft.nbt.NbtHelper", "net.minecraft.nbt.NbtUtils")
			replace("net.minecraft.registry.RegistryWrapper.WrapperLookup", "net.minecraft.core.HolderLookup.Provider")
			replace("net.minecraft.registry.RegistryWrapper", "net.minecraft.core.HolderLookup")
			replace("net.minecraft.registry.tag.DamageTypeTags", "net.minecraft.tags.DamageTypeTags")
			replace("net.minecraft.block.entity.ChestLidAnimator", "net.minecraft.world.level.block.entity.ChestLidController")
			replace("net.minecraft.block.entity.ViewerCountManager", "net.minecraft.world.level.block.entity.ContainerOpenersCounter")
			replace("net.minecraft.block.entity.LidOpenable", "net.minecraft.world.level.block.entity.LidBlockEntity")
			replace("net.minecraft.client.model.ModelPart", "net.minecraft.client.model.geom.ModelPart")
			replace("net.minecraft.client.render.entity.model.VillagerResemblingModel", "net.minecraft.client.model.npc.VillagerModel")
			replace("net.minecraft.world.chunk.ChunkSection", "net.minecraft.world.level.chunk.LevelChunkSection")
			replace("net.minecraft.world.chunk.Chunk", "net.minecraft.world.level.chunk.ChunkAccess")
			replace("net.minecraft.util.shape.VoxelShapes", "net.minecraft.world.phys.shapes.Shapes")
			replace("net.minecraft.state.property.IntProperty", "net.minecraft.world.level.block.state.properties.IntegerProperty")
			replace("RegistryWrapper.WrapperLookup", "HolderLookup.Provider")
			replace("net.minecraft.util.math.Direction.Type", "net.minecraft.core.Direction.Plane")
			replace("net.minecraft.entity.ai.goal.GoalSelector", "net.minecraft.world.entity.ai.goal.GoalSelector")
			replace("net.minecraft.particle.ParticleEffect", "net.minecraft.core.particles.ParticleOptions")
			replace("net.minecraft.component.DataComponentTypes", "net.minecraft.core.component.DataComponents")
		}

		// Simple Yarn names whose official names differ. Word boundaries so WorkerMob / AreaContainers
		// are left alone. Reverse patterns look for official names, which the Yarn source does not use.
		regex(current.parsed >= "26.1") {
			replace("""\bServerWorld\b""" to "ServerLevel", """\bServerLevel\b""" to "ServerWorld")
			replace("""\bWorldView\b""" to "LevelReader", """\bLevelReader\b""" to "WorldView")
			replace("""\bWorldAccess\b""" to "LevelAccessor", """\bLevelAccessor\b""" to "WorldAccess")
			replace("""\bBlockView\b""" to "BlockGetter", """\bBlockGetter\b""" to "BlockView")
			replace("""\bServerPlayerEntity\b""" to "ServerPlayer", """\bServerPlayer\b""" to "ServerPlayerEntity")
			replace("""\bPlayerEntity\b""" to "Player", """\bPlayer\b""" to "PlayerEntity")
			replace("""\bPlayerInventory\b""" to "net.minecraft.world.entity.player.Inventory", """net\.minecraft\.world\.entity\.player\.Inventory""" to "PlayerInventory")
			replace("""\bBlockBox\b""" to "BoundingBox", """\bBoundingBox\b""" to "BlockBox")
			replace("""\bAbstractHorseEntity\b""" to "AbstractHorse", """\bAbstractHorse\b""" to "AbstractHorseEntity")
			replace("""\bAnimalEntity\b""" to "Animal", """\bAnimal\b""" to "AnimalEntity")
			replace("""\bCowEntity\b""" to "Cow", """\bCow\b""" to "CowEntity")
			replace("""\bTameableEntity\b""" to "TamableAnimal", """\bTamableAnimal\b""" to "TameableEntity")
			replace("""\bVillagerEntity\b""" to "Villager", """\bVillager\b""" to "VillagerEntity")
			replace("""\bMobEntity\b""" to "Mob", """\bMob\b""" to "MobEntity")
			replace("""\bSpawnGroup\b""" to "MobCategory", """\bMobCategory\b""" to "SpawnGroup")
			replace("""\bTrackedDataHandlerRegistry\b""" to "EntityDataSerializers", """\bEntityDataSerializers\b""" to "TrackedDataHandlerRegistry")
			replace("""\bTrackedDataHandler\b""" to "EntityDataSerializer", """\bEntityDataSerializer\b""" to "TrackedDataHandler")
			replace("""\bLandPathNodeMaker\b""" to "WalkNodeEvaluator", """\bWalkNodeEvaluator\b""" to "LandPathNodeMaker")
			replace("""\bPathNodeNavigator\b""" to "PathFinder", """\bPathFinder\b""" to "PathNodeNavigator")
			replace("""\bMobNavigation\b""" to "GroundPathNavigation", """\bGroundPathNavigation\b""" to "MobNavigation")
			replace("""\bPathNodeType\b""" to "PathType", """\bPathType\b""" to "PathNodeType")
			replace("""\bNbtCompound\b""" to "CompoundTag", """\bCompoundTag\b""" to "NbtCompound")
			replace("""\bNbtList\b""" to "ListTag", """\bListTag\b""" to "NbtList")
			replace("""\bNbtElement\b""" to "Tag", """\bTag\b""" to "NbtElement")
			replace("""\bMutableText\b""" to "MutableComponent", """\bMutableComponent\b""" to "MutableText")
			replace("""\bItemPlacementContext\b""" to "BlockPlaceContext", """\bBlockPlaceContext\b""" to "ItemPlacementContext")
			replace("""\bItemGroup\b""" to "CreativeModeTab", """\bCreativeModeTab\b""" to "ItemGroup")
			replace("""\bSimpleInventory\b""" to "SimpleContainer", """\bSimpleContainer\b""" to "SimpleInventory")
			replace("""\bInventories\b""" to "ContainerHelper", """\bContainerHelper\b""" to "Inventories")
			replace("""\bGenericContainerScreenHandler\b""" to "ChestMenu", """\bChestMenu\b""" to "GenericContainerScreenHandler")
			replace("""\bNamedScreenHandlerFactory\b""" to "MenuProvider", """\bMenuProvider\b""" to "NamedScreenHandlerFactory")
			replace("""\bScreenHandler\b""" to "AbstractContainerMenu", """\bAbstractContainerMenu\b""" to "ScreenHandler")
			replace("""\bScreenTexts\b""" to "CommonComponents", """\bCommonComponents\b""" to "ScreenTexts")
			replace("""\bBlockSoundGroup\b""" to "SoundType", """\bSoundType\b""" to "BlockSoundGroup")
			replace("""\bSoundCategory\b""" to "SoundSource", """\bSoundSource\b""" to "SoundCategory")
			replace("""\bPistonBehavior\b""" to "PushReaction", """\bPushReaction\b""" to "PistonBehavior")
			replace("""\bBlockRenderType\b""" to "RenderShape", """\bRenderShape\b""" to "BlockRenderType")
			replace("""\bBlockWithEntity\b""" to "BaseEntityBlock", """\bBaseEntityBlock\b""" to "BlockWithEntity")
			replace("""\bShapeContext\b""" to "CollisionContext", """\bCollisionContext\b""" to "ShapeContext")
			replace("""\bLootableContainerBlockEntity\b""" to "RandomizableContainerBlockEntity", """\bRandomizableContainerBlockEntity\b""" to "LootableContainerBlockEntity")
			replace("""\bAbstractBlock\b""" to "BlockBehaviour", """\bBlockBehaviour\b""" to "AbstractBlock")
			replace("""\bSaplingGenerator\b""" to "TreeGrower", """\bTreeGrower\b""" to "SaplingGenerator")
			replace("""\bDefaultedList\b""" to "NonNullList", """\bNonNullList\b""" to "DefaultedList")
			replace("""\bMathHelper\b""" to "Mth", """\bMth\b""" to "MathHelper")
			replace("""\bRotationAxis\b""" to "Axis", """com\.mojang\.math\.Axis""" to "RotationAxis")
			replace("""\bVec3d\b""" to "Vec3", """\bVec3\b""" to "Vec3d")
			replace("""\bActionResult\b""" to "InteractionResult", """\bInteractionResult\b""" to "ActionResult")
			replace("""\bBlockMirror\b""" to "Mirror", """\bMirror\b""" to "BlockMirror")
			replace("""\bBlockRotation\b""" to "Rotation", """\bRotation\b""" to "BlockRotation")
			replace("""\bFormatting\b""" to "ChatFormatting", """\bChatFormatting\b""" to "Formatting")
			replace("""\bItemScatterer\b""" to "Containers", """\bContainers\b""" to "ItemScatterer")
			replace("""\bClientPlayPacketListener\b""" to "ClientGamePacketListener", """\bClientGamePacketListener\b""" to "ClientPlayPacketListener")
			replace("""\bBlockEntityUpdateS2CPacket\b""" to "ClientboundBlockEntityDataPacket", """\bClientboundBlockEntityDataPacket\b""" to "BlockEntityUpdateS2CPacket")
			replace("""\bCustomPayload\b""" to "CustomPacketPayload", """\bCustomPacketPayload\b""" to "CustomPayload")
			replace("""\bPacketCodecs\b""" to "ByteBufCodecs", """\bByteBufCodecs\b""" to "PacketCodecs")
			replace("""\bPacketCodec\b""" to "StreamCodec", """\bStreamCodec\b""" to "PacketCodec")
			replace("""\bRegistryByteBuf\b""" to "RegistryFriendlyByteBuf", """\bRegistryFriendlyByteBuf\b""" to "RegistryByteBuf")
			replace("""\bPacketByteBuf\b""" to "FriendlyByteBuf", """\bFriendlyByteBuf\b""" to "PacketByteBuf")
			replace("""\bDrawContext\b""" to "GuiGraphicsExtractor", """\bGuiGraphicsExtractor\b""" to "DrawContext")
			replace("""\bButtonWidget\b""" to "Button", """\bButton\b""" to "ButtonWidget")
			replace("""\bClickableWidget\b""" to "AbstractWidget", """\bAbstractWidget\b""" to "ClickableWidget")
			replace("""\bElementListWidget\b""" to "ObjectSelectionList", """\bObjectSelectionList\b""" to "ElementListWidget")
			replace("""\bSliderWidget\b""" to "AbstractSliderButton", """\bAbstractSliderButton\b""" to "SliderWidget")
			replace("""\bKeyBinding\b""" to "KeyMapping", """\bKeyMapping\b""" to "KeyBinding")
			replace("""\bInputUtil\b""" to "InputConstants", """\bInputConstants\b""" to "InputUtil")
			replace("""\bMatrixStack\b""" to "PoseStack", """\bPoseStack\b""" to "MatrixStack")
			replace("""\bModelTransformationMode\b""" to "ItemDisplayContext", """\bItemDisplayContext\b""" to "ModelTransformationMode")
			replace("""\bBlockEntityRendererFactory\b""" to "BlockEntityRendererProvider", """\bBlockEntityRendererProvider\b""" to "BlockEntityRendererFactory")
			replace("""\bFeatureRendererContext\b""" to "RenderLayerParent", """\bRenderLayerParent\b""" to "FeatureRendererContext")
			replace("""\bEntityModelLayers\b""" to "ModelLayers", """\bModelLayers\b""" to "EntityModelLayers")
			replace("""\bVillagerResemblingModel\b""" to "VillagerModel", """\bVillagerModel\b""" to "VillagerResemblingModel")
			replace("""\bEntityRendererFactory\b""" to "EntityRendererProvider", """\bEntityRendererProvider\b""" to "EntityRendererFactory")
			replace("""\bMobEntityRenderer\b""" to "MobRenderer", """\bMobRenderer\b""" to "MobEntityRenderer")
			replace("""\bVertexConsumerProvider\b""" to "MultiBufferSource", """\bMultiBufferSource\b""" to "VertexConsumerProvider")
			replace("""\bMinecraftClient\b""" to "Minecraft", """\bMinecraft\b""" to "MinecraftClient")
			replace("""\bFabricItemGroup\b""" to "FabricCreativeModeTab", """\bFabricCreativeModeTab\b""" to "FabricItemGroup")
			replace("""\bKeyBindingHelper\b""" to "KeyMappingHelper", """\bKeyMappingHelper\b""" to "KeyBindingHelper")
			replace("""\bBlockRenderLayerMap\b""" to "ChunkSectionLayerMap", """\bChunkSectionLayerMap\b""" to "BlockRenderLayerMap")
			replace("""\bPacketByteBufs\b""" to "FriendlyByteBufs", """\bFriendlyByteBufs\b""" to "PacketByteBufs")
			replace("""\bRegistries\b""" to "BuiltInRegistries", """\bBuiltInRegistries\b""" to "Registries")
			replace("""\bWorld\b""" to "Level", """\bLevel\b""" to "World")
			replace("""\bText\b""" to "Component", """\bComponent\b""" to "Text")
			replace("""\bHand\b""" to "InteractionHand", """\bInteractionHand\b""" to "Hand")
			replace("""\bBox\b""" to "AABB", """\bAABB\b""" to "Box")
			replace("""(?<!\.)\bInventory\b""" to "Container", """(?<!\.)\bContainer\b""" to "Inventory")
			replace("""\bPathAwareEntity\b""" to "PathfinderMob", """\bPathfinderMob\b""" to "PathAwareEntity")
			replace("""\bEntityNavigation\b""" to "PathNavigation", """\bPathNavigation\b""" to "EntityNavigation")
			replace("""\bNavigationType\b""" to "PathComputationType", """\bPathComputationType\b""" to "NavigationType")
			replace("""\bDefaultAttributeContainer\b""" to "AttributeSupplier", """\bAttributeSupplier\b""" to "DefaultAttributeContainer")
			replace("""\bEntityAttributes\b""" to "Attributes", """\bAttributes\b""" to "EntityAttributes")
			replace("""\bDataTracker\b""" to "SynchedEntityData", """\bSynchedEntityData\b""" to "DataTracker")
			replace("""\bTrackedData\b""" to "EntityDataAccessor", """\bEntityDataAccessor\b""" to "TrackedData")
			replace("""\bNbtHelper\b""" to "NbtUtils", """\bNbtUtils\b""" to "NbtHelper")
			replace("""\bRegistryWrapper\b""" to "HolderLookup", """\bHolderLookup\b""" to "RegistryWrapper")
			replace("""\bChestLidAnimator\b""" to "ChestLidController", """\bChestLidController\b""" to "ChestLidAnimator")
			replace("""\bViewerCountManager\b""" to "ContainerOpenersCounter", """\bContainerOpenersCounter\b""" to "ViewerCountManager")
			replace("""\bLidOpenable\b""" to "LidBlockEntity", """\bLidBlockEntity\b""" to "LidOpenable")
			replace("""\bLookAtEntityGoal\b""" to "LookAtPlayerGoal", """\bLookAtPlayerGoal\b""" to "LookAtEntityGoal")
			replace("""\bLookAroundGoal\b""" to "RandomLookAroundGoal", """\bRandomLookAroundGoal\b""" to "LookAroundGoal")
			replace("""\bSwimGoal\b""" to "FloatGoal", """\bFloatGoal\b""" to "SwimGoal")
			replace("""\bBlockStateParticleEffect\b""" to "BlockParticleOption", """\bBlockParticleOption\b""" to "BlockStateParticleEffect")
			replace("""\bVoxelShapes\b""" to "Shapes", """\bShapes\b""" to "VoxelShapes")
			replace("""\bDirectionProperty\b""" to "EnumProperty<Direction>", """EnumProperty<Direction>""" to "DirectionProperty")
			replace("""\bIntProperty\b""" to "IntegerProperty", """\bIntegerProperty\b""" to "IntProperty")
			replace("""Direction\.Type""" to "Direction.Plane", """Direction\.Plane""" to "Direction.Type")
			replace("""\bGENERIC_MAX_HEALTH\b""" to "MAX_HEALTH", """\bMAX_HEALTH\b""" to "GENERIC_MAX_HEALTH")
			replace("""\bGENERIC_MOVEMENT_SPEED\b""" to "MOVEMENT_SPEED", """\bMOVEMENT_SPEED\b""" to "GENERIC_MOVEMENT_SPEED")
			replace("""\bGENERIC_FOLLOW_RANGE\b""" to "FOLLOW_RANGE", """\bFOLLOW_RANGE\b""" to "GENERIC_FOLLOW_RANGE")
			replace("""\bGENERIC_ATTACK_DAMAGE\b""" to "ATTACK_DAMAGE", """\bATTACK_DAMAGE\b""" to "GENERIC_ATTACK_DAMAGE")
			replace("""\bPACKET_CODEC\b""" to "STREAM_CODEC", """\bSTREAM_CODEC\b""" to "PACKET_CODEC")
			replace("""UNLIMITED_NBT_COMPOUND""" to "TRUSTED_COMPOUND_TAG", """TRUSTED_COMPOUND_TAG""" to "UNLIMITED_NBT_COMPOUND")
			replace("""ByteBufCodecs\.toList\(\)""" to "ByteBufCodecs.list()", """ByteBufCodecs\.list\(\)""" to "ByteBufCodecs.toList()")
			replace("""\.collect\(ByteBufCodecs\.list\(\)\)""" to ".apply(ByteBufCodecs.list())", """\.apply\(ByteBufCodecs\.list\(\)\)""" to ".collect(ByteBufCodecs.toList())")
			replace("""\.tuple\(""" to ".composite(", """\.composite\(""" to ".tuple(")
			replace("""CustomPacketPayload> getId\(\)""" to "CustomPacketPayload> type()", """CustomPayload> type\(\)""" to "CustomPayload> getId()")
			replace("""\bId<""" to "Type<", """CustomPacketPayload\.Type<""" to "Id<")
			replace("""NonNullList\.ofSize""" to "NonNullList.withSize", """NonNullList\.withSize""" to "NonNullList.ofSize")
			replace("""VoxelShapes\.union""" to "Shapes.or", """Shapes\.or""" to "VoxelShapes.union")
			replace("""\.nonOpaque\(\)""" to ".noOcclusion()", """\.noOcclusion\(\)""" to ".nonOpaque()")
			replace("""\.burnable\(\)""" to ".ignitedByLava()", """\.ignitedByLava\(\)""" to ".burnable()")
			replace("""\.sounds\(""" to ".sound(", """___blockSounds___""" to ".sounds(")
			replace("""\.pistonBehavior\(""" to ".pushReaction(", """\.pushReaction\(""" to ".pistonBehavior(")
			replace("""\.solidBlock\(""" to ".isRedstoneConductor(", """\.isRedstoneConductor\(""" to ".solidBlock(")
			replace("""Settings\.create\(""" to "Properties.of(", """Properties\.of\(""" to "Settings.create(")
			replace("""Properties\.create\(""" to "Properties.of(", """___propCreate___""" to "Properties.create(")
			replace("""\bItem\.Settings\b""" to "Item.Properties", """\bItem\.Properties\b""" to "Item.Settings")
			replace("""IntegerProperty\.of""" to "IntegerProperty.create", """___intPropOf___""" to "IntegerProperty.of")
			replace("""\bgetDefaultState\b""" to "defaultBlockState", """\bdefaultBlockState\b""" to "getDefaultState")
			replace("""\bsetDefaultState\b""" to "registerDefaultState", """\bregisterDefaultState\b""" to "setDefaultState")
			replace("""\bgetStateManager\b""" to "getStateDefinition", """\bgetStateDefinition\b""" to "getStateManager")
			replace("""\bappendProperties\b""" to "createBlockStateDefinition", """\bcreateBlockStateDefinition\b""" to "appendProperties")
			replace("""\bgetOutlineShape\b""" to "getShape", """\bgetShape\b""" to "getOutlineShape")
			replace("""\bgetRenderType\b""" to "getRenderShape", """\bgetRenderShape\b""" to "getRenderType")
			replace("""\bhasComparatorOutput\b""" to "hasAnalogOutputSignal", """\bhasAnalogOutputSignal\b""" to "hasComparatorOutput")
			replace("""\bgetComparatorOutput\b""" to "getAnalogOutputSignal", """\bgetAnalogOutputSignal\b""" to "getComparatorOutput")
			replace("""\bcanPathfindThrough\b""" to "isPathfindable", """\bisPathfindable\b""" to "canPathfindThrough")
			replace("""\bcreateScreenHandlerFactory\b""" to "getMenuProvider", """\bgetMenuProvider\b""" to "createScreenHandlerFactory")
			replace("""\bopenHandledScreen\b""" to "openMenu", """\bopenMenu\b""" to "openHandledScreen")
			replace("""\bcreateScreenHandler\b""" to "createMenu", """\bcreateMenu\b""" to "createScreenHandler")
			replace("""createGeneric9x6""" to "sixRows", """sixRows""" to "createGeneric9x6")
			replace("""calculateComparatorOutput""" to "getRedstoneSignalFromBlockEntity", """getRedstoneSignalFromBlockEntity""" to "calculateComparatorOutput")
			replace("""\bvalidateTicker\b""" to "createTickerHelper", """___validateTicker___""" to "validateTicker")
			replace("""\bgetHeldStacks\b""" to "getItems", """___getHeldStacks___""" to "getHeldStacks")
			replace("""\bsetHeldStacks\b""" to "setItems", """___setHeldStacks___""" to "setHeldStacks")
			replace("""\btoInitialChunkDataNbt\b""" to "getUpdateTag", """\bgetUpdateTag\b""" to "toInitialChunkDataNbt")
			replace("""\btoUpdatePacket\b""" to "getUpdatePacket", """\bgetUpdatePacket\b""" to "toUpdatePacket")
			replace("""\bwriteLootTable\b""" to "trySaveLootTable", """\btrySaveLootTable\b""" to "writeLootTable")
			replace("""\breadLootTable\b""" to "tryLoadLootTable", """\btryLoadLootTable\b""" to "readLootTable")
			replace("""\bmarkDirty\b""" to "setChanged", """\bsetChanged\b""" to "markDirty")
			replace("""\.increment\(""" to ".grow(", """\.grow\(""" to ".increment(")
			replace("""(?<!Mc)\.isOf\(""" to ".is(", """___isOf___""" to ".isOf(")
			replace("""\.isClient\(\)""" to ".isClientSide()", """\.isClientSide\(\)""" to ".isClient()")
			replace("""\.isClient\b""" to ".isClientSide", """\.isClientSide\b""" to ".isClient")
			replace("""\bgetTime\(\)""" to "getGameTime()", """\bgetGameTime\(\)""" to "getTime()")
			replace("""\btoImmutable\(\)""" to "immutable()", """\bimmutable\(\)""" to "toImmutable()")
			replace("""\.up\(\)""" to ".above()", """\.above\(\)""" to ".up()")
			replace("""\bcontainsId\b""" to "containsKey", """___containsId___""" to "containsId")
			replace("""\bisSneaking\b""" to "isShiftKeyDown", """\bisShiftKeyDown\b""" to "isSneaking")
			replace("""\bgetHorizontalPlayerFacing\b""" to "getHorizontalDirection", """\bgetHorizontalDirection\b""" to "getHorizontalPlayerFacing")
			replace("""\bcreativeMode\b""" to "instabuild", """\binstabuild\b""" to "creativeMode")
			replace("""\bdataTracker\b""" to "entityData", """\bentityData\b""" to "dataTracker")
			replace("""\binitDataTracker\b""" to "defineSynchedData", """\bdefineSynchedData\b""" to "initDataTracker")
			replace("""\bwriteCustomDataToNbt\b""" to "addAdditionalSaveData", """\baddAdditionalSaveData\b""" to "writeCustomDataToNbt")
			replace("""\breadCustomDataFromNbt\b""" to "readAdditionalSaveData", """\breadAdditionalSaveData\b""" to "readCustomDataFromNbt")
			replace("""\bgetUuid\b""" to "getUUID", """\bgetUUID\b""" to "getUuid")
			replace("""\bsetPersistent\b""" to "setPersistenceRequired", """\bsetPersistenceRequired\b""" to "setPersistent")
			replace("""\bwasPressed\b""" to "consumeClick", """\bconsumeClick\b""" to "wasPressed")
			replace("""\bsquaredDistanceTo\b""" to "distanceToSqr", """\bdistanceToSqr\b""" to "squaredDistanceTo")
			replace("""\bcannotPickup\b""" to "hasPickUpDelay", """\bhasPickUpDelay\b""" to "cannotPickup")
			replace("""\bcanInsert\b""" to "canAddItem", """\bcanAddItem\b""" to "canInsert")
			replace("""\bgetStackInHand\b""" to "getItemInHand", """\bgetItemInHand\b""" to "getStackInHand")
			replace("""\bsetStackInHand\b""" to "setItemInHand", """\bsetItemInHand\b""" to "setStackInHand")
			replace("""\bgetWidth\(\)""" to "getBbWidth()", """\bgetBbWidth\(\)""" to "getWidth()")
			replace("""\bonPlaced\b""" to "setPlacedBy", """\bsetPlacedBy\b""" to "onPlaced")
			replace("""\bonUseWithItem\b""" to "useItemOn", """\buseItemOn\b""" to "onUseWithItem")
			replace("""\bonUse\b""" to "useWithoutItem", """___onUse___""" to "onUse")
			replace("""\bgetCodec\b""" to "codec", """___getCodec___""" to "getCodec")
			replace("""\bcreateCodec\b""" to "simpleCodec", """\bsimpleCodec\b""" to "createCodec")
			replace("""Containers\.spawn""" to "Containers.dropContents", """Containers\.dropContents""" to "Containers.spawn")
			replace("""\.generator\b""" to ".treeGrower", """\.treeGrower\b""" to ".generator")
			replace("""\bmegaVariant\b""" to "megaTree", """\bmegaTree\b""" to "megaVariant")
			replace("""\bregularVariant\b""" to "tree", """___regularVariant___""" to "regularVariant")
			replace("""RenderLayer\.getCutout\(\)""" to "RenderType.cutout()", """RenderType\.cutout\(\)""" to "RenderLayer.getCutout()")
			replace("""RenderLayer\.getLines\(\)""" to "RenderType.lines()", """RenderType\.lines\(\)""" to "RenderLayer.getLines()")
			replace("""RenderLayer\.getDebugQuads\(\)""" to "RenderType.debugQuads()", """RenderType\.debugQuads\(\)""" to "RenderLayer.getDebugQuads()")
			replace("""RenderLayer\.getEntityCutoutNoCull""" to "RenderType.entityCutout", """RenderType\.entityCutout""" to "RenderLayer.getEntityCutoutNoCull")
			replace("""OverlayTexture\.DEFAULT_UV""" to "OverlayTexture.NO_OVERLAY", """OverlayTexture\.NO_OVERLAY""" to "OverlayTexture.DEFAULT_UV")
			replace("""\.getPositionMatrix\(\)""" to ".pose()", """\.pose\(\)""" to ".getPositionMatrix()")
			replace("""\.getNormalMatrix\(\)""" to ".normal()", """\.normal\(\)""" to ".getNormalMatrix()")
			replace("""getRegistryManager\(\)""" to "registryAccess()", """registryAccess\(\)""" to "getRegistryManager()")
			replace("""\.offset\(direction\)""" to ".relative(direction)", """\.relative\(direction\)""" to ".offset(direction)")
			replace("""\.offset\(face\)""" to ".relative(face)", """\.relative\(face\)""" to ".offset(face)")
			replace("""\.offset\(side\)""" to ".relative(side)", """\.relative\(side\)""" to ".offset(side)")
			replace("""\.with\(FACING""" to ".setValue(FACING", """\.setValue\(FACING""" to ".with(FACING")
			replace("""\.get\(FACING""" to ".getValue(FACING", """\.getValue\(FACING""" to ".get(FACING")
			replace("""\.with\(LEVEL""" to ".setValue(LEVEL", """\.setValue\(LEVEL""" to ".with(LEVEL")
			replace("""\.get\(LEVEL""" to ".getValue(LEVEL", """\.getValue\(LEVEL""" to ".get(LEVEL")
			replace("""\.with\(FenceGateBlock\.OPEN""" to ".setValue(FenceGateBlock.OPEN", """\.setValue\(FenceGateBlock\.OPEN""" to ".with(FenceGateBlock.OPEN")
			replace("""\.get\(FenceGateBlock\.OPEN""" to ".getValue(FenceGateBlock.OPEN", """\.getValue\(FenceGateBlock\.OPEN""" to ".get(FenceGateBlock.OPEN")
			replace("""\.get\(AttachedStemBlock\.FACING""" to ".getValue(AttachedStemBlock.FACING", """\.getValue\(AttachedStemBlock\.FACING""" to ".get(AttachedStemBlock.FACING")
			replace("""\.with\(OPEN""" to ".setValue(OPEN", """___with_open___""" to ".with(OPEN")
			replace("""builder\.add\(SKIN""" to "builder.define(SKIN", """builder\.define\(SKIN""" to "builder.add(SKIN")
			replace("""builder\.add\(BURIED""" to "builder.define(BURIED", """builder\.define\(BURIED""" to "builder.add(BURIED")
			replace("""builder\.add\(DISGUISE""" to "builder.define(DISGUISE", """builder\.define\(DISGUISE""" to "builder.add(DISGUISE")
			replace("""stack\.contains\(net\.minecraft\.core\.component\.DataComponents\.FOOD\)""" to "stack.has(net.minecraft.core.component.DataComponents.FOOD)", """stack\.has\(net\.minecraft\.core\.component\.DataComponents\.FOOD\)""" to "stack.contains(net.minecraft.component.DataComponentTypes.FOOD)")
			replace("""\bgetMaxCountPerStack\b""" to "getMaxStackSize", """\bgetMaxStackSize\b""" to "getMaxCountPerStack")
			replace("""\bPassiveEntity\b""" to "AgeableMob", """\bAgeableMob\b""" to "PassiveEntity")
			replace("""\bClientPlayerEntity\b""" to "LocalPlayer", """\bLocalPlayer\b""" to "ClientPlayerEntity")
			replace("""\bChunkSectionPos\b""" to "SectionPos", """\bSectionPos\b""" to "ChunkSectionPos")
			replace("""\bWorldEvents\b""" to "LevelEvent", """___WorldEvents___""" to "WorldEvents")
			replace("""\bStateManager\b""" to "StateDefinition", """___StateManager___""" to "StateManager")
			replace("""\bPathContext\b""" to "PathfindingContext", """\bPathfindingContext\b""" to "PathContext")
			replace("""Properties\.HORIZONTAL_FACING""" to "BlockStateProperties.HORIZONTAL_FACING", """BlockStateProperties\.HORIZONTAL_FACING""" to "Properties.HORIZONTAL_FACING")
			replace("""Block\.createCuboidShape""" to "Block.box", """Block\.box""" to "Block.createCuboidShape")
			replace("""Vec3d\.ofCenter""" to "Vec3.atCenterOf", """Vec3\.atCenterOf""" to "Vec3d.ofCenter")
			replace("""DefaultedList\.ofSize""" to "NonNullList.withSize", """___ofSize___""" to "DefaultedList.ofSize")
			replace("""BlockPos\.Mutable""" to "BlockPos.MutableBlockPos", """BlockPos\.MutableBlockPos""" to "BlockPos.Mutable")
			replace("""\bswingHand\b""" to "swing", """___swingHand___""" to "swingHand")
			replace("""\bisChunkLoaded\b""" to "hasChunk", """\bhasChunk\b""" to "isChunkLoaded")
			replace("""\bisIdle\b""" to "isDone", """___navIdle___""" to "isIdle")
			replace("""\.isIn\(""" to ".is(", """___isIn___""" to ".isIn(")
			replace("""\.down\(\)""" to ".below()", """\.below\(\)""" to ".down()")
			replace("""\breachesTarget\b""" to "canReach", """\bcanReach\b""" to "reachesTarget")
			replace("""TrackedDataHandlerRegistry\.INTEGER""" to "EntityDataSerializers.INT", """EntityDataSerializers\.INT""" to "TrackedDataHandlerRegistry.INTEGER")
			replace("""EntityDataSerializers\.INTEGER""" to "EntityDataSerializers.INT", """___serInt___""" to "EntityDataSerializers.INTEGER")
			replace("""\bstartMovingTo\b""" to "moveTo", """___startMovingTo___""" to "startMovingTo")
			replace("""\bfindPathTo\b""" to "createPath", """___findPathTo___""" to "findPathTo")
			replace("""\bstartMovingAlong\b""" to "moveTo", """___startMovingAlong___""" to "startMovingAlong")
			replace("""\bgetCurrentPath\b""" to "getPath", """___getCurrentPath___""" to "getCurrentPath")
			replace("""\bgetCurrentNodeIndex\b""" to "getNextNodeIndex", """\bgetNextNodeIndex\b""" to "getCurrentNodeIndex")
			replace("""path\.getLength\(\)""" to "path.getNodeCount()", """path\.getNodeCount\(\)""" to "path.getLength()")
			replace("""\bisTouchingWater\b""" to "isInWater", """\bisInWater\b""" to "isTouchingWater")
			replace("""\bsendEntityStatus\b""" to "broadcastEntityEvent", """\bbroadcastEntityEvent\b""" to "sendEntityStatus")
			replace("""\.expand\(""" to ".inflate(", """\.inflate\(""" to ".expand(")
			replace("""\bgetSquaredDistance\b""" to "distSqr", """\bdistSqr\b""" to "getSquaredDistance")
			replace("""goalSelector\.add\(""" to "goalSelector.addGoal(", """goalSelector\.addGoal\(""" to "goalSelector.add(")
			replace("""getLookControl\(\)\.lookAt""" to "getLookControl().setLookAt", """getLookControl\(\)\.setLookAt""" to "getLookControl().lookAt")
			replace("""\bgetEntitiesByClass\b""" to "getEntitiesOfClass", """\bgetEntitiesOfClass\b""" to "getEntitiesByClass")
			replace("""\bspawnEntity\b""" to "addFreshEntity", """\baddFreshEntity\b""" to "spawnEntity")
			replace("""\brefreshPositionAndAngles\b""" to "snapTo", """\bsnapTo\b""" to "refreshPositionAndAngles")
			replace("""\bcreateBlockEntity\b""" to "newBlockEntity", """\bnewBlockEntity\b""" to "createBlockEntity")
			replace("""\bgetCachedState\b""" to "getBlockState", """___getCachedState___""" to "getCachedState")
			replace("""\bisFinished\b""" to "isDone", """___pathFinished___""" to "isFinished")
			replace("""\bgetBreedingAge\b""" to "getAge", """___getBreedingAge___""" to "getBreedingAge")
			replace("""item\.getStack\(\)""" to "item.getItem()", """item\.getItem\(\)""" to "item.getStack()")
			replace("""item\.setStack\(""" to "item.setItem(", """item\.setItem\(""" to "item.setStack(")
			replace("""\.addStack\(""" to ".addItem(", """___addStack___""" to ".addStack(")
			replace("""\bisBreedingItem\b""" to "isFood", """___isBreedingItem___""" to "isBreedingItem")
			replace("""\bcanEat\b""" to "canFallInLove", """\bcanFallInLove\b""" to "canEat")
			replace("""\bgrowUp\b""" to "ageUp", """\bageUp\b""" to "growUp")
			replace("""toGrowUpAge""" to "getSpeedUpSecondsWhenFeeding", """getSpeedUpSecondsWhenFeeding""" to "toGrowUpAge")
			replace("""\bcreatePathNodeNavigator\b""" to "createPathFinder", """___createPathNodeNavigator___""" to "createPathNodeNavigator")
			replace("""\bnodeMaker\b""" to "nodeEvaluator", """\bnodeEvaluator\b""" to "nodeMaker")
			replace("""\bgetDefaultNodeType\b""" to "getPathType", """___getDefaultNodeType___""" to "getDefaultNodeType")
			replace("""setCanEnterOpenDoors""" to "setCanPassDoors", """setCanPassDoors""" to "setCanEnterOpenDoors")
			replace("""\bcanImmediatelyDespawn\b""" to "removeWhenFarAway", """\bremoveWhenFarAway\b""" to "canImmediatelyDespawn")
			replace("""\brendersOutsideBoundingBox\b""" to "shouldRenderOffScreen", """\bshouldRenderOffScreen\b""" to "rendersOutsideBoundingBox")
			replace("""\bgetRenderDistance\b""" to "getViewDistance", """\bgetViewDistance\b""" to "getRenderDistance")
			replace("""\bupdateNeighborsAlways\b""" to "updateNeighborsAt", """\bupdateNeighborsAt\b""" to "updateNeighborsAlways")
			replace("""\bupdateComparators\b""" to "updateNeighbourForOutputSignal", """\bupdateNeighbourForOutputSignal\b""" to "updateComparators")
			replace("""matrices\.peek\(\)""" to "matrices.last()", """matrices\.last\(\)""" to "matrices.peek()")
			replace("""matrices\.push\(\)""" to "matrices.pushPose()", """matrices\.pushPose\(\)""" to "matrices.push()")
			replace("""matrices\.pop\(\)""" to "matrices.popPose()", """matrices\.popPose\(\)""" to "matrices.pop()")
			replace("""\.vertex\(matrix""" to ".addVertex(matrix", """\.addVertex\(matrix""" to ".vertex(matrix")
			replace("""getNode\(index\)\.getBlockPos\(\)""" to "getNode(index).asBlockPos()", """getNode\(index\)\.asBlockPos\(\)""" to "getNode(index).getBlockPos()")
			replace("""BlockPos\.fromLong""" to "BlockPos.of", """___fromLong___""" to "BlockPos.fromLong")
			replace("""BlockPos\.ofFloored""" to "BlockPos.containing", """BlockPos\.containing""" to "BlockPos.ofFloored")
			replace("""MapColor\.OAK_TAN""" to "MapColor.WOOD", """MapColor\.WOOD""" to "MapColor.OAK_TAN")
			replace("""BuiltInRegistries\.ITEM_GROUP""" to "BuiltInRegistries.CREATIVE_MODE_TAB", """BuiltInRegistries\.CREATIVE_MODE_TAB""" to "BuiltInRegistries.ITEM_GROUP")
			replace("""\.displayName\(""" to ".title(", """\.title\(""" to ".displayName(")
			replace("""\.textRenderer\b""" to ".font", """\.font\b""" to ".textRenderer")
			replace("""\.currentScreenHandler\b""" to ".containerMenu", """\.containerMenu\b""" to ".currentScreenHandler")
			replace("""\bbodyYaw\b""" to "yBodyRot", """\byBodyRot\b""" to "bodyYaw")
			replace("""\bheadYaw\b""" to "yHeadRot", """\byHeadRot\b""" to "headYaw")
			replace("""\bprevBodyYaw\b""" to "yBodyRotO", """\byBodyRotO\b""" to "prevBodyYaw")
			replace("""\bprevHeadYaw\b""" to "yHeadRotO", """\byHeadRotO\b""" to "prevHeadYaw")
			replace("""\bprevYaw\b""" to "yRotO", """\byRotO\b""" to "prevYaw")
			replace("""\bprevX\b""" to "xo", """___prevX___""" to "prevX")
			replace("""\bprevZ\b""" to "zo", """___prevZ___""" to "prevZ")
			replace("""\bpitch\b""" to "xRot", """___pitch___""" to "pitch")
			replace("""ENTITYBLOCK_ANIMATED""" to "INVISIBLE", """___ENTITYBLOCK_ANIMATED___""" to "ENTITYBLOCK_ANIMATED")
			replace("""SoundEvents\.ENTITY_VILLAGER_HURT""" to "SoundEvents.VILLAGER_HURT", """SoundEvents\.VILLAGER_HURT""" to "SoundEvents.ENTITY_VILLAGER_HURT")
			replace("""SoundEvents\.ENTITY_VILLAGER_DEATH""" to "SoundEvents.VILLAGER_DEATH", """SoundEvents\.VILLAGER_DEATH""" to "SoundEvents.ENTITY_VILLAGER_DEATH")
			replace("""SoundEvents\.ENTITY_ITEM_PICKUP""" to "SoundEvents.ITEM_PICKUP", """SoundEvents\.ITEM_PICKUP""" to "SoundEvents.ENTITY_ITEM_PICKUP")
			replace("""SoundEvents\.ENTITY_GENERIC_EAT""" to "SoundEvents.GENERIC_EAT", """SoundEvents\.GENERIC_EAT""" to "SoundEvents.ENTITY_GENERIC_EAT")
			replace("""SoundEvents\.ENTITY_GENERIC_BIG_FALL""" to "SoundEvents.GENERIC_BIG_FALL", """SoundEvents\.GENERIC_BIG_FALL""" to "SoundEvents.ENTITY_GENERIC_BIG_FALL")
			replace("""SoundEvents\.ENTITY_COW_MILK""" to "SoundEvents.COW_MILK", """SoundEvents\.COW_MILK""" to "SoundEvents.ENTITY_COW_MILK")
			replace("""SoundEvents\.BLOCK_CHEST_OPEN""" to "SoundEvents.CHEST_OPEN", """SoundEvents\.CHEST_OPEN""" to "SoundEvents.BLOCK_CHEST_OPEN")
			replace("""SoundEvents\.BLOCK_CHEST_CLOSE""" to "SoundEvents.CHEST_CLOSE", """SoundEvents\.CHEST_CLOSE""" to "SoundEvents.BLOCK_CHEST_CLOSE")
			replace("""SoundEvents\.BLOCK_FENCE_GATE_OPEN""" to "SoundEvents.FENCE_GATE_OPEN", """SoundEvents\.FENCE_GATE_OPEN""" to "SoundEvents.BLOCK_FENCE_GATE_OPEN")
			replace("""SoundEvents\.BLOCK_FENCE_GATE_CLOSE""" to "SoundEvents.FENCE_GATE_CLOSE", """SoundEvents\.FENCE_GATE_CLOSE""" to "SoundEvents.BLOCK_FENCE_GATE_CLOSE")
			replace("""SoundEvents\.ITEM_CROP_PLANT""" to "SoundEvents.CROP_PLANTED", """SoundEvents\.CROP_PLANTED""" to "SoundEvents.ITEM_CROP_PLANT")
			replace("""SoundEvents\.ITEM_HOE_TILL""" to "SoundEvents.HOE_TILL", """SoundEvents\.HOE_TILL""" to "SoundEvents.ITEM_HOE_TILL")
			replace("""SoundEvents\.ITEM_BUCKET_FILL""" to "SoundEvents.BUCKET_FILL", """SoundEvents\.BUCKET_FILL""" to "SoundEvents.ITEM_BUCKET_FILL")
			replace("""SoundEvents\.ITEM_BUCKET_EMPTY""" to "SoundEvents.BUCKET_EMPTY", """SoundEvents\.BUCKET_EMPTY""" to "SoundEvents.ITEM_BUCKET_EMPTY")
			replace("""SoundEvents\.ITEM_FIRECHARGE_USE""" to "SoundEvents.FIRECHARGE_USE", """SoundEvents\.FIRECHARGE_USE""" to "SoundEvents.ITEM_FIRECHARGE_USE")
			replace("""ButtonWidget\.PressAction""" to "Button.OnPress", """Button\.OnPress""" to "ButtonWidget.PressAction")
			replace("""\bPressAction\b""" to "OnPress", """\bOnPress\b""" to "PressAction")
			replace("""\bChunkSection\b""" to "LevelChunkSection", """\bLevelChunkSection\b""" to "ChunkSection")
			replace("""\.isClient\b""" to ".isClientSide()", """___isClientField___""" to ".isClient")
			replace("""\.random\b""" to ".getRandom()", """___worldRandom___""" to ".random")
			replace("""NbtHelper\.fromBlockPos""" to "NbtUtils.writeBlockPos", """___fromBlockPos___""" to "NbtHelper.fromBlockPos")
			replace("""NbtHelper\.toBlockPos""" to "NbtUtils.readBlockPos", """___toBlockPos___""" to "NbtHelper.toBlockPos")
			replace("""(?<!minecraft\.)\bworld\b""" to "level", """___worldIdent___""" to "world")
			replace("""\bregisterData\b""" to "defineId", """\bdefineId\b""" to "registerData")
			replace("""\bsetBlockState\b""" to "setBlock", """___setBlockState___""" to "setBlockState")
			replace("""\bbreakBlock\b""" to "destroyBlock", """\bdestroyBlock\b""" to "breakBlock")
			replace("""\baddSyncedBlockEvent\b""" to "blockEvent", """\bblockEvent\b""" to "addSyncedBlockEvent")
			replace("""DataTracker\.registerData""" to "SynchedEntityData.defineId", """___registerData___""" to "DataTracker.registerData")
			replace("""\bgetWorld\b""" to "getLevel", """___getWorld___""" to "getWorld")
			replace("""(?<!util\.)\bRandom\b""" to "RandomSource", """___mcRandom___""" to "Random")
			replace("""\.color\(1\.0F""" to ".setColor(1.0F", """___vertexColor___""" to ".color(1.0F")
			replace("""\.color\(""" to ".setColor(", """___anyColor___""" to ".color(")
			replace("""\.entries\(""" to ".displayItems(", """\.displayItems\(""" to ".entries(")
			replace("""registerKeyBinding""" to "registerKeyMapping", """registerKeyMapping""" to "registerKeyBinding")
			replace("""playC2S\(\)""" to "serverboundPlay()", """serverboundPlay\(\)""" to "playC2S()")
			replace("""playS2C\(\)""" to "clientboundPlay()", """clientboundPlay\(\)""" to "playS2C()")
			replace("""CustomPayload> getId\(\)""" to "CustomPacketPayload> type()", """CustomPayload> type\(\)""" to "CustomPayload> getId()")
			replace("""\.collect\(PacketCodecs\.toList\(\)\)""" to ".apply(ByteBufCodecs.list())", """\.apply\(ByteBufCodecs\.list\(\)\)""" to ".collect(PacketCodecs.toList())")
			replace("""ItemScatterer\.spawn""" to "Containers.dropContents", """___itemScattererSpawn___""" to "ItemScatterer.spawn")
			replace("""\bgetContainerName\b""" to "getDefaultName", """\bgetDefaultName\b""" to "getContainerName")
			replace("""\binitGoals\b""" to "registerGoals", """\bregisterGoals\b""" to "initGoals")
			replace("""\.decrement\(""" to ".shrink(", """\.shrink\(""" to ".decrement(")
			replace("""\.getLayerModelPart\(""" to ".bakeLayer(", """\.bakeLayer\(""" to ".getLayerModelPart(")
			replace("""\.addFeature\(""" to ".addLayer(", """\.addLayer\(""" to ".addFeature(")
			replace("""matrices\.multiply\(""" to "matrices.mulPose(", """matrices\.mulPose\(""" to "matrices.multiply(")
			replace("""RotationAxis\.POSITIVE_Y""" to "Axis.YP", """Axis\.YP""" to "RotationAxis.POSITIVE_Y")
			replace("""\bElement\b""" to "GuiEventListener", """\bGuiEventListener\b""" to "Element")
			replace("""\bSelectable\b""" to "NarratableEntry", """\bNarratableEntry\b""" to "Selectable")
			replace("""drawTextWithShadow""" to "text", """___drawTextWithShadow___""" to "drawTextWithShadow")
			replace("""\.fontHeight\b""" to ".lineHeight", """\.lineHeight\b""" to ".fontHeight")
			replace("""open\.getInventory\(\)""" to "open.getContainer()", """open\.getContainer\(\)""" to "open.getInventory()")
			replace("""\bisShearable\b""" to "readyForShearing", """\breadyForShearing\b""" to "isShearable")
			replace("""\bonContainerOpen\b""" to "onOpen", """___onContainerOpen___""" to "onContainerOpen")
			replace("""\bonContainerClose\b""" to "onClose", """___onContainerClose___""" to "onContainerClose")
			replace("""\bonViewerCountUpdate\b""" to "openerCountChanged", """\bopenerCountChanged\b""" to "onViewerCountUpdate")
			replace("""\bisPlayerViewing\b""" to "isOwnContainer", """\bisOwnContainer\b""" to "isPlayerViewing")
			replace("""lid\.step\(\)""" to "lid.tickLid()", """lid\.tickLid\(\)""" to "lid.step()")
			replace("""lid\.getProgress""" to "lid.getOpenness", """lid\.getOpenness""" to "lid.getProgress")
			replace("""lid\.setOpen""" to "lid.shouldBeOpen", """lid\.shouldBeOpen""" to "lid.setOpen")
			replace("""\bgetAnimationProgress\b""" to "getOpenNess", """\bgetOpenNess\b""" to "getAnimationProgress")
			replace("""\bonSyncedBlockEvent\b""" to "triggerEvent", """\btriggerEvent\b""" to "onSyncedBlockEvent")
			replace("""IntProperty\.of""" to "IntegerProperty.create", """___intOf___""" to "IntProperty.of")
		}
	}
}
